### ISSUE TITLE
TypeError: callback is not a function 

### ISSUE THREAD

**Issue by mrknmc** [brightcove/hot-shots#152]
Hi,

We're running into an issue when we call `increment` without a callback argument, e.g.:

```
baseStatsD.increment('exception-handler.exception', 1, tags)
```

and the socket is `null` (this can happen if the socket is not successfully created by the metric server - in our case Datadog agent), `callback` is called with an error (https://github.com/brightcove/hot-shots/blob/master/lib/statsd.js#L361-L363).

However, callback is undefined so this fails with the following trace:

Full trace:
```
TypeError: callback is not a function 
at Client.sendMessage (/usr/src/app/node_modules/hot-shots/lib/statsd.js:362:12)
at Client._send (/usr/src/app/node_modules/hot-shots/lib/statsd.js:306:12)
at Client.send (/usr/src/app/node_modules/hot-shots/lib/statsd.js:283:8)
at Client.sendStat (/usr/src/app/node_modules/hot-shots/lib/statsd.js:260:8)
at Client.sendAll (/usr/src/app/node_modules/hot-shots/lib/statsd.js:236:10)
at Client.increment (/usr/src/app/node_modules/hot-shots/lib/statsFunctions.js:114:10) 
```

**Comment by bdeitte** [comment]
published in 6.8.7
