### ISSUE TITLE
Error: send EINVAL ::1:8125 on Node.js 17+

### ISSUE THREAD

**Issue by francisdb** [brightcove/hot-shots#222]
`hot-shots` `9.0.0`
`Darwin foobar.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64`

we configure `StatsD` by default with `host` `localhost`

on Node.js 16 everything works as expected
on Node.js 17 and 18 we get:

```
 Unhandled error. (Error: Error sending hot-shots message: Error: send EINVAL ::1:8125

      at handleCallback (node_modules/hot-shots/lib/statsd.js:350:32)
      at processTicksAndRejections (node:internal/process/task_queues:81:21) {
        code: 'EINVAL'
      })
      at handleCallback (node_modules/hot-shots/lib/statsd.js:367:21)
```

Probably because localhost now resolves to `::1` instead of `127.0.0.1` and the code path expects an ipv4 address?

workaround is to configure `127.0.0.1` instead of `localhost`

**Comment by bdeitte** [comment]
Well, that's interesting.  I'm surprised this isn't coming up with more people.  Switching away from localhost just happened in version 8.0.0 and was done for performance reasons: https://github.com/brightcove/hot-shots/pull/186
