### ISSUE TITLE
Hotshots client not writing to telegraf server in process.on('exit') blocks, so I can't send exit codes as metrics

### ISSUE THREAD

**Issue by meyerkev** [brightcove/hot-shots#239]
Update: This is because our socket calls aren't calling their callbacks.  

I stick a console.log('Handling Callback') into 

```
  const handleCallback = (err, bytes) => {
    console.log("Handling callback")
```
in lib/statsd.js

Before process.on('exit')

```
iccservice                  | Trace: socket send
iccservice                  |     at Object.send (/src/node_modules/hot-shots/lib/transport.js:81:17)
iccservice                  |     at Client.sendMessage (/src/node_modules/hot-shots/lib/statsd.js:399:17)
iccservice                  |     at Client._send (/src/node_modules/hot-shots/lib/statsd.js:298:12)
iccservice                  |     at Client.send (/src/node_modules/hot-shots/lib/statsd.js:263:8)
iccservice                  |     at Client.sendStat (/src/node_modules/hot-shots/lib/statsd.js:239:8)
iccservice                  |     at Client.sendAll (/src/node_modules/hot-shots/lib/statsd.js:215:10)
iccservice                  |     at Client.gauge (/src/node_modules/hot-shots/lib/statsFunctions.js:200:10)
iccservice                  |     at Timeout.statsdDevices [as _onTimeout] (/src/src/message/metrics.js:39:16)
iccservice                  |     at listOnTimeout (node:internal/timers:559:17)
iccservice                  |     at processTimers (node:internal/timers:502:7)
iccservice                  | Handling callback
```

```
iccservice                  | Trace: socket send
iccservice                  |     at Object.send (/src/node_modules/hot-shots/lib/transport.js:81:17)
iccservice                  |     at Client.sendMessage (/src/node_modules/hot-shots/lib/statsd.js:398:17)
iccservice                  |     at Client._send (/src/node_modules/hot-shots/lib/statsd.js:298:12)
iccservice                  |     at Client.send (/src/node_modules/hot-shots/lib/statsd.js:263:8)
iccservice                  |     at Client.sendStat (/src/node_modules/hot-shots/lib/statsd.js:239:8)
iccservice                  |     at Client.sendAll (/src/node_modules/hot-shots/lib/statsd.js:215:10)
iccservice                  |     at Client.increment (/src/node_modules/hot-shots/lib/statsFunctions.js:138:10)
iccservice                  |     at process.<anonymous> (file:///src/src/index.mjs:152:33)
iccservice                  |     at process.emit (node:events:513:28)
iccservice                  |     at process.emit (node:domain:489:12)
iccservice                  |     at process._fatalException (node:internal/process/execution:156:19)
```

(Ignore the line numbers, I'm doing printf debugging + breakpoints)

So what I think is happening is that the socket call doesn't work because you're never allowed to go async in process.on('exit')  

I don't know for sure, but I do know that that socket call doesn't call its callback because I put a breakpoint on it and it fires outside of process.on('exit'), but not in it.  So once you've caught an unhandled exception, there's no good way to send metrics from your application and we can't containerize/orchestrate this, so I guess we're going to run a 3rd-party application that does nothing but run a StatsD call, wait for the callbacks, then quit.  

Original Post: 

When I write metrics synchronously, I get metrics out

When I write metrics from process.on('uncaughtExceptionMonitor') or process.on('exit') blocks, the log messages all show up in my stderr, none of my metrics send.  What am I doing wrong on hotshots 9.3.0?

```javascript
//None of this works
process.on('unhandledRejection', (reason, p) => {
    Logger.error(`Unhandled Rejection at: Promise ${p} reason: ${reason.stack}`, reason)
    if (manualDI) {
        // One day, we will get a real monitoring system in place that comes with events and therefore dict tagging
        // Until then, we'll just use statsD
        Logger.debug('Incrementing unhandledRejection metric')
        manualDI.statsD.increment('iccservice.unhandledRejection', [`instance-os.hostname()`])
        Logger.debug('Incremented unhandledRejection metric')
    }
})

// TODO: Because we catch unhandedRejection, we could change this to uncaughtException
//       Though if we did that, we'd need to explicitly crash as per docs
process.on('uncaughtExceptionMonitor', (err, origin) => {
    Logger.error('Uncaught exception, process will terminate.', err)
    if (manualDI) {
        // One day, we will get a real monitoring system in place that comes with events and therefore dict tagging
        // Until then, we'll just use statsD
        Logger.debug('Incrementing uncaughtException metric')
        manualDI.statsD.increment('iccservice.uncaughtException', [`instance-${os.hostname()}`])
        Logger.debug('Incremented uncaughtException metric')
    }
})

process.on('exit', (code) => {
    Logger.debug(`Process is exiting with code: ${code}`)
    if (manualDI && manualDI.statsD) {
        if (code !== 0) {
            manualDI.statsD.increment('iccservice.exit_code.nonzero_exit', /*[`code-${code}`, `instance-${os.hostname()}`]*/)
            Logger.debug('Incremented nonzero_exit metric')
        } else {
            manualDI.statsD.increment('iccservice.exit_code.zero_exit' [`instance-${os.hostname()}`])
            Logger.debug('Incremented zero_exit metric')
        }
        manualDI.statsD.close((err) => {
            Logger.Error('The StatsD close did not work quite right: ', err);
        })
    }
    
})

//But this works
manualDI.statsD.increment('iccservice.startup', [`success`, `instance-${os.hostname()}`])

setTimeout(() => {  throw Error('test error'); }, 10000);
```

**Comment by meyerkev** [comment]
So I did some code searching in a forked repo and I _think_ what's happening is that on the on-close when we try to flush, we do a non-synchronous socket send and then there's no callback handler to let us cycle until we've finished flushing.  

And this is very very awkward.

**Comment by meyerkev** [comment]
OK, so what I think is happening even more is that we're not tracking socket sends so if we do a sudden shutdown, there's no finally block saying "Hey, wait up, you're in the middle of sending 3 metrics"

I have ripped libs/statsd.js to shreds adding callbacks and synchronous infinite while loops until callback done.
