### ISSUE TITLE
Calling increment with only args results in corrupted packets

### ISSUE THREAD

**Issue by kpdecker** [brightcove/hot-shots#33]
```
    dogstatsd.increment('express.response.error', [
      `url:${(req.route && req.route.path) || Sanitize.url(req.url)}`,
      `statusCode:${req.statusCode}`
    ]);
```

I had assumed that the above would default to value of 1, but it does not, resulting in error in the dogstats agent.

```
2016-10-24 10:41:09 CDT | ERROR | dd.dogstatsd | dogstatsd(dogstatsd.py:366) | Error receiving datagram
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/dogstatsd.py", line 354, in start
    aggregator_submit(message)
  File "/opt/datadog-agent/agent/aggregator.py", line 608, in submit_packets
    parsed_packets = self.parse_metric_packet(packet)
  File "/opt/datadog-agent/agent/aggregator.py", line 465, in parse_metric_packet
    raise Exception('Unparseable metric packet: %s' % packet)
Exception: Unparseable metric packet: express.response.error:url:/not-found,statusCode:null|c
```

Adding a conditional like the following seems to fix the issue

```
    if (arguments.length < 3) {
      if (typeof value !== 'number') {
        tags = value;
        value = undefined;
      }
    }
```

**Comment by bdeitte** [comment]
That seems reasonable to me.  Would you like to open a PR with this fix and a test?  If not, I'll just keep this issue open until someone picks this up.  Thanks.

**Comment by jsocol** [comment]
Opened #42!
